import { z } from "zod";

// Base Schema for the Campus
export const CampusSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  // bounds is a GeoJSON string or parsed object from PostGIS
  bounds: z.any(), 
});
export type Campus = z.infer<typeof CampusSchema>;

// Base Schema for Buildings
export const BuildingSchema = z.object({
  id: z.string().uuid(),
  campus_id: z.string().uuid(),
  name: z.string(),
  outline: z.any(),
});
export type Building = z.infer<typeof BuildingSchema>;

// Base Schema for Rooms
export const RoomSchema = z.object({
  id: z.string().uuid(),
  building_id: z.string().uuid(),
  floor: z.string(),
  name: z.string(),
  geom: z.any(),
  centroid: z.any().optional(), // Generated by DB
});
export type Room = z.infer<typeof RoomSchema>;

// THE DATA CONTRACT FOR TRACK B
export const RoutingEdgeSchema = z.object({
  id: z.string().uuid(),
  source_node_id: z.string().uuid(),
  target_node_id: z.string().uuid(),
  distance_meters: z.number().positive(),
  is_accessible: z.boolean(),
  floor_id: z.string(),
});
export type RoutingEdge = z.infer<typeof RoutingEdgeSchema>;

// POI Schema
export const POISchema = z.object({
  id: z.string().uuid(),
  room_id: z.string().uuid(),
  name: z.string(),
  category: z.string(),
  tags: z.array(z.string()),
});
export type POI = z.infer<typeof POISchema>;
