import { z } from "zod";

// Base Schema for the Campus
export const CampusSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  // bounds is a GeoJSON string or parsed object from PostGIS
  bounds: z.any(), 
});
export type Campus = z.infer<typeof CampusSchema>;

// Base Schema for Buildings
export const BuildingSchema = z.object({
  id: z.string().uuid(),
  campus_id: z.string().uuid(),
  name: z.string(),
  outline: z.any(),
});
export type Building = z.infer<typeof BuildingSchema>;

// Base Schema for Rooms
export const RoomSchema = z.object({
  id: z.string().uuid(),
  building_id: z.string().uuid(),
  floor: z.string(),
  name: z.string(),
  geom: z.any(),
  centroid: z.any().optional(), // Generated by DB
});
export type Room = z.infer<typeof RoomSchema>;

// THE DATA CONTRACT FOR TRACK B
export const RoutingEdgeSchema = z.object({
  id: z.string().uuid(),
  source_node_id: z.string().uuid(),
  target_node_id: z.string().uuid(),
  distance_meters: z.number().positive(),
  is_accessible: z.boolean(),
  floor_id: z.string(),
});
export type RoutingEdge = z.infer<typeof RoutingEdgeSchema>;

// POI Schema
export const POISchema = z.object({
  id: z.string().uuid(),
  room_id: z.string().uuid(),
  name: z.string(),
  category: z.string(),
  tags: z.array(z.string()),
});
export type POI = z.infer<typeof POISchema>;

// POI search result (includes ts_rank)
export const POISearchResultSchema = POISchema.extend({
  rank: z.number(),
});
export type POISearchResult = z.infer<typeof POISearchResultSchema>;

// Campus metadata (campus + buildings + POI counts)
export const CampusMetadataSchema = z.object({
  campus: CampusSchema,
  buildings: z.array(z.object({
    id: z.string().uuid(),
    name: z.string(),
    outline: z.any(),
    floors: z.array(z.string()),
  })),
  poiCounts: z.array(z.object({
    category: z.string(),
    count: z.number(),
  })),
});
export type CampusMetadata = z.infer<typeof CampusMetadataSchema>;

// Obstruction report (DB row)
export const ObstructionReportSchema = z.object({
  id: z.string().uuid(),
  room_id: z.string().uuid().nullable(),
  edge_id: z.string().uuid().nullable(),
  description: z.string(),
  reported_at: z.date(),
});
export type ObstructionReport = z.infer<typeof ObstructionReportSchema>;

// Create obstruction report (POST body)
export const CreateObstructionReportSchema = z.object({
  roomId: z.string().uuid().optional(),
  edgeId: z.string().uuid().optional(),
  description: z.string().min(1).max(1000),
  lng: z.number().min(-180).max(180).optional(),
  lat: z.number().min(-90).max(90).optional(),
});
export type CreateObstructionReportInput = z.infer<typeof CreateObstructionReportSchema>;
